### ISSUE TITLE
Support for JSX files

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-dev-utils#11]

**Comment by amcclain** [comment]
Might just be this line in current version:

https://github.com/exhi/hoist-dev-utils/blob/3a557507f89c20e520458f62abde5f95a7fc383f/configureWebpack.js#L186

Let us know if this is something we want right away and can test, or we could have Arjun fold this requirement into the Webpack 4 update.

**Comment by nadkarniarjun** [comment]
Spoke with Lee about this, and I'm going to try and fold it into the Webpack 4 upgrade. If the upgrade goes longer than this week, we will fallback to including it in the v3 version.

**Comment by nadkarniarjun** [comment]
Hi. I've added this into the webpack4Uprade branch, and Anselm has also added it in the master branch as well.
