### ISSUE TITLE
Remove dependency on favicons-webpack-plugin

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-dev-utils#3]
The `favicons-webpack-plugin` plugin causes some difficulties behind corporate proxies due to the dependency on phantomjs. 

For now we can just remove this plugin and use the standard favicon support in webpack.

**Comment by amcclain** [comment]
We have been surviving pretty well with this dep and its baggage - closing, can re-open if it becomes a bigger problem in another environment.
